### ISSUE TITLE
Get proxies information from HTTP_PROXY / HTTPS_PROXY environment variables 

### ISSUE THREAD

**Issue by imanolpadillo** [threema-ch/threema-msgapi-sdk-python#58] opened 2021-09-01 12:25 UTC
By default "trust_env" variable is false, so aiohttp.ClientSession does not get information from HTTP_PROXY / HTTPS_PROXY environment variables. For this reason, the following code was received:

`aiohttp.client_exceptions.ClientConnectorError: Cannot connect to host msgapi.threema.ch:443 ssl:default [Name or service not known]`

In order to fix this issue, it is necessary to modify "_gateway.py" module, including in __init__ the following line:
`self._session = session if session is not None else aiohttp.ClientSession(trust_env=True)`

[_gateway.zip](https://github.com/lgrahl/threema-msgapi-sdk-python/files/7090981/_gateway.zip)

**Comment by lgrahl** [comment] 2021-09-01 12:49
Duplicate of #54. You can provide your own aiohttp.Session instance by passing it into the `Connection` constructor. I'm open for a PR to have an option in the CLI to set this.

Do you need it for the CLI?

**Closed as completed by lgrahl** 2021-09-01 12:49 UTC
Labels: duplicate
