### ISSUE TITLE
Invalid environment marker: python_version<="3.4"

### ISSUE THREAD

**Issue by APajonk** [threema-ch/threema-msgapi-sdk-python#33] opened 2017-05-24 21:39 UTC
`:/tmp/threema-msgapi-sdk-python-3.0.4# pip3 install .
Unpacking /tmp/threema-msgapi-sdk-python-3.0.4
  Running setup.py (path:/tmp/pip-42xc6mwq-build/setup.py) egg_info for package from file:///tmp/threema-msgapi-sdk-python-3.0.4
    error in threema.gateway setup command: Invalid environment marker: python_version<="3.4"
    Complete output from command python setup.py egg_info:
    error in threema.gateway setup command: Invalid environment marker: python_version<="3.4"`

Tested clean installation with Release 3.0.4 on an Cubietruck with Python 3.4.2

**Comment by dbrgn** [comment] 2017-05-24 22:24
You probably have a very old version of setuptools. You can check with `python -c 'import setuptools; print(setuptools.__version__)'`. Latest version is 35.0.2. I think the feature we need was introduced around 20.

The best way to update your package would probably be via system package manager (if it offers a newer version) or via "pip3 install -U setuptools".

**Comment by lgrahl** [comment] 2017-05-24 22:38
I suggest creating a virtual environment first and then updating setuptools in that environment. Let us know if that helps.

**Comment by APajonk** [comment] 2017-05-25 20:59
Thanks, updating setuptools helped. The package in Armbian Image comes below version 10. But checking "./threema-gateway version" after setup leads to new error now... Again a missing or outdated package?

`Traceback (most recent call last):
  File "/usr/local/bin/./threema-gateway", line 6, in <module>
    from pkg_resources import load_entry_point
  File "/usr/local/lib/python3.4/dist-packages/pkg_resources/__init__.py", line 3036, in <module>
    @_call_aside
  File "/usr/local/lib/python3.4/dist-packages/pkg_resources/__init__.py", line 3020, in _call_aside
    f(*args, **kwargs)
  File "/usr/local/lib/python3.4/dist-packages/pkg_resources/__init__.py", line 3049, in _initialize_master_working_set
    working_set = WorkingSet._build_master()
  File "/usr/local/lib/python3.4/dist-packages/pkg_resources/__init__.py", line 654, in _build_master
    ws.require(__requires__)
  File "/usr/local/lib/python3.4/dist-packages/pkg_resources/__init__.py", line 968, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/usr/local/lib/python3.4/dist-packages/pkg_resources/__init__.py", line 854, in resolve
    raise DistributionNotFound(req, requirers)
pkg_resources.DistributionNotFound: The 'typing<3.7,>=3.6' distribution was not found and is required by threema.gateway`

**Comment by APajonk** [comment] 2017-05-25 21:04
Searching for Python "typing" module leaded me to a Github repository which says: "This GitHub repo is used for development of the typing module defined by PEP 484. The module is available in Python since version 3.5.0 on a provisional basis until Python 3.7.0." - https://github.com/python/typing

So is it possible that current Threema Gateway releases now need at least Python v.3.5.x? Until now I thought it is at least 3.4.x?

**Comment by APajonk** [comment] 2017-05-25 21:17
Installed https://github.com/python/asyncio and https://github.com/python/typing by hand, seems that release 3.0.4 is working now:

`:/# /usr/local/bin/./threema-gateway version`
`Version: 3.0.4`
`Feature Level: 3`

Or would you guys prefer going to a higher Pyton version? 3.5.x or 3.6.x?

**Comment by lgrahl** [comment] 2017-05-25 21:32
The *typing* module is a backport and is available for Python 3.4, see [here](https://pypi.python.org/pypi/typing/3.6.1). All the dependencies you mentioned should be installed automatically. If they don't, it's a bug and we have to know which tool versions you've installed and what commands you've used.

> Or would you guys prefer going to a higher Pyton version? 3.5.x or 3.6.x?

It really doesn't matter. Everything from Python 3.4 on will work.

**Comment by APajonk** [comment] 2017-05-28 13:21
Did nothing special for installation. Simply standard pip3 install with the published releases of both packages.

For asyncio v3.4.3 I did for example:
`cd /tmp/`
`wget https://github.com/python/asyncio/archive/3.4.3.tar.gz`
`tar xfvz 3.4.3.tar.gz`
`cd /tmp/asyncio-3.4.3/`
`pip3 install .`

Analogous to typing (found here: https://github.com/python/typing/archive/3.6.1.tar.gz)

**Comment by lgrahl** [comment] 2017-05-31 10:28
I cannot reproduce this. One further note: You should definitively use PyPI `pip install threema.gateway` unless you want to contribute to this module. Any further questions or can this issue be closed?

**Comment by lgrahl** [comment] 2017-09-21 11:02
I'll close this for now. Please reopen if it's still an issue for you.

**Closed as completed by lgrahl** 2017-09-21 11:02 UTC
